### PR TITLE
pass down initial location nameto autocomplete field when editing a case

### LINKED ISSUE #416: Location name isn't shown in location input field when editing the case
**Describe the bug**
cf title

**To Reproduce**
1. add a case
2. edit the case
3. observe that the location field doesn't have the initial value set

### PR DESCRIPTION
**Pull request by attwad**
When something exists:

image

When you click on the field:
image

When you change:
image

Fixes #416

### CODE REVIEW

File: verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx [hunk 1]
```diff
@@ -122,7 +128,7 @@ export function PlacesAutocomplete(
                 setInputValue(newInputValue);
             }}
             renderInput={(params): JSX.Element => (
-                <div>
+                <>
```
Comment (allysonjp715) [inline verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx:131]: Interesting. This can be used to group the fields into one Element to return?

File: verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx [hunk 2]
```diff
@@ -132,7 +138,13 @@ export function PlacesAutocomplete(
                         name="unused"
                         required={props.required}
                         data-testid={props.name}
-                        label="Location"
+                        // Use the initial valuelocation name as a hint when untouched
```
Comment (allysonjp715) [inline verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx:141]: Is there not a defaultValue that can be used rather than changing the label?

Comment (attwad) [reply verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx:141]: nope, tried hard but {value}, {text}, {initialValue}, {defaultValue} etc nothing worked except label.

File: verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx (hunk 1 above)
Comment (attwad) [reply verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx:131]: yes, I've been using it plenty, super useful :)

File: verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx (hunk 2 above)
Comment (allysonjp715) [reply verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx:141]: Hm that's a shame. The material UI TextField component has a defaultValue field: https://material-ui.com/api/text-field/ Maybe we could try using that TextField rather than the formik-material-ui one? I thought all the formik-material-ui components passed through props to the material-ui component... shame it's not working as expected.

Comment (attwad) [reply verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx:141]: good idea, let me try with that field now and merge if I don't get anywhere...

Comment (attwad) [reply verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx:141]: nopenopenope considering this a _good enough_ fix for now to not not lose too much time on it...

FTR got a mixed bags of errors like
```
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```

or `TypeError: Cannot read property 'isSubmitting' of undefined` when trying to use something else than the current TextField :(
